//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using UnityStandardAssets._2D;

public class shoot : MonoBehaviour
{
	public Projectile 	bulletPrefab;
	public float 		speed = 5;

	void Start() {

	}

	void Update() {
		if (Input.GetKeyDown (KeyCode.S)) {
			bulletPrefab.right = GetComponent<PlatformerCharacter2D> ().m_FacingRight;
			Instantiate(bulletPrefab, transform.position, Quaternion.identity);	

		}
	}
}


